### ISSUE TITLE
Wrong value type on `$this->expectedField()` breaks test, but assert still passes.

### ISSUE THREAD

**Issue by justlevine** [wp-graphql/wp-graphql-testcase#15]
**Describe the bug**
(Apologies in advance, not entirely sure how to describe this).

When passing a value of the wrong type to `$this->expectedField( $path, $value )`, future `$this->expectedField()` calls are broken, but `$this->assertQuerySuccessful()` still passes.

**To Reproduce**
```php
protected function testBadType()  : void {
   $query = 'query myQuery {
    posts {
      nodes {
        content
        databaseId
        postId
        slug
      }
    }
  }';

  $response = $this->graphql( compact( 'query' ) );
  
  $expected = [
    $this->expectedObject( 
      'posts',
      [
        $this->expectedNode(
          'nodes',
          [
            $this->expectedField( 'postId', 1 ) // This will work fine, since its the correct type.
            $this->expectedField( 'databaseId', '1' ) // This is where things get wonky. Note the value is a string.
            $this->expectedField( 'content', 'test content' ) // This gets replaced in assertQuerySuccessful with the previous
            $this->expectedField( 'slug', 'test' ) // This doesnt even get tested in assertQuerySuccessful
          ]
        ),
      ]
  ];
  
  codecept_debug( $expected ); // All the fields appear correctly.
  
  $this->assertQuerySuccessful( $response, $expected,  ); // passes.
}
```

So here's what's weird. The `$expected` array created is correct. However, when it runs through `$this->assertQuerySuccessful()`, you get the following log:
```jsonc
// databseId
{
    "WANTED VALUE": "1",
    "VALUES_AT_LOCATION": [
        1
    ]
} 
// replaces content
{
    "WANTED_VALUE": "1",
    "ACTUAL_DATA": 1
}
// no slug
```
  
The `content` gets replaced with a similar but not exact `databaseId` field check, and the `slug` field is ignored entirely.

**Expected behavior**
Ideally a type mismatch fails, but either way the rest of the assert still needs to be evaluated.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04 (WSL 2), devilbox.
- WPGraphQL: 1.6.10
- WPGraphQL Test Case: 2.1.3

**Comment by kidunot89** [comment]
@justlevine You fix was officially release in `v2.2.0`
